---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: src/routes/_home/home.md
  label: Home Page
- type: document
  path: src/routes/about/_about.md
  label: About Page
- type: directory
  path: authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: posts
  label: Recipes
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
